# Generated by Django 2.0.9 on 2018-12-05 20:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BEConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('regex_file', models.FileField(blank=True, null=True, upload_to='regex_files/')),
                ('ssn_mode', models.IntegerField(choices=[(0, 'Labeled "SSN:" (strictest)'), (1, 'No SSN, dashes required (default)'), (2, 'No dashes required (least strict)')], default=1)),
                ('pii_scanners', models.BooleanField(default=True)),
                ('web_scanners', models.BooleanField(default=False)),
                ('exif_gps_scanners', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BESession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_path', models.TextField()),
                ('disk_image', models.BooleanField(default=False)),
                ('named_entity_extraction', models.BooleanField(default=False)),
                ('feature_files_path', models.TextField(blank=True)),
                ('annotated_feature_files_path', models.TextField(blank=True)),
                ('dfxml_path', models.TextField(blank=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('processing_failure', models.BooleanField(default=False)),
                ('processing_complete', models.BooleanField(default=False)),
                ('be_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.BEConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_file', models.CharField(max_length=50)),
                ('forensic_path', models.TextField(blank=True)),
                ('offset', models.TextField(blank=True)),
                ('feature', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField(blank=True)),
                ('filepath', models.TextField(blank=True)),
                ('date_modified', models.CharField(blank=True, max_length=50)),
                ('date_created', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('allocated', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('be_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.BESession')),
            ],
        ),
        migrations.CreateModel(
            name='RedactedSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('redaction_type', models.IntegerField(choices=[(0, 'Log only'), (1, 'Remove files'), (2, 'Redact features (scrub)'), (3, 'Redact features (replace)'), (4, 'Redact features within disk image')], default=1)),
                ('unallocated_files', models.BooleanField(default=False)),
                ('redacted_set_path', models.TextField(blank=True)),
                ('processing_failure', models.BooleanField(default=False)),
                ('processing_complete', models.BooleanField(default=False)),
                ('redaction_log', models.TextField(blank=True)),
                ('be_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redacted_sets', to='api.BESession')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.File'),
        ),
    ]
