# Generated by Django 2.0.6 on 2018-06-11 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BESession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('be_started', models.DateTimeField()),
                ('be_finished', models.DateTimeField()),
                ('be_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.BEConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_file', models.CharField(max_length=50)),
                ('forensic_path', models.CharField(max_length=100)),
                ('offset', models.IntegerField()),
                ('feature', models.TextField()),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('filepath', models.TextField()),
                ('date_modified', models.CharField(max_length=40)),
                ('date_created', models.CharField(max_length=40)),
                ('redacted', models.BooleanField(default=False)),
                ('note', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transfer',
            name='disk_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source_path',
            field=models.FileField(default='file.txt', upload_to='transfers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.Transfer'),
        ),
        migrations.AddField(
            model_name='feature',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.File'),
        ),
        migrations.AddField(
            model_name='besession',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.Transfer'),
        ),
    ]
