# Generated by Django 2.0.6 on 2018-06-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180611_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besession',
            name='be_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='besession',
            name='be_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
