# Generated by Django 2.0.6 on 2018-06-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180611_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='transfer',
        ),
        migrations.AddField(
            model_name='file',
            name='be_session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.BESession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
