# Generated by Django 2.0.6 on 2018-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_besession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='allocated',
            field=models.BooleanField(default=True),
        ),
    ]
