# Generated by Django 2.0.6 on 2018-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180611_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='besession',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
