# Generated by Django 2.0.6 on 2018-06-12 20:32

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_besession_processing_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besession',
            name='be_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
