# Generated by Django 2.0.6 on 2018-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180612_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='besession',
            old_name='annotated_be_feature_files',
            new_name='annotated_feature_files_path',
        ),
        migrations.RenameField(
            model_name='besession',
            old_name='be_feature_files',
            new_name='feature_files_path',
        ),
        migrations.RemoveField(
            model_name='besession',
            name='be_finished',
        ),
        migrations.RemoveField(
            model_name='besession',
            name='be_started',
        ),
        migrations.AddField(
            model_name='besession',
            name='be_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='besession',
            name='dfxml',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='besession',
            name='dfxml_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='besession',
            name='features_annotated',
            field=models.BooleanField(default=False),
        ),
    ]
