# Generated by Django 2.0.6 on 2018-06-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_besession_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='context',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='forensic_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='offset',
            field=models.IntegerField(null=True),
        ),
    ]
