# Generated by Django 2.0.6 on 2018-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180619_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='beconfig',
            name='ssn_mode',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
        ),
    ]
