# Generated by Django 2.0.6 on 2018-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_beconfig_ssn_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beconfig',
            name='ssn_mode',
            field=models.IntegerField(choices=[(0, 'Labeled "SSN:" (strictest)'), (1, 'No SSN, dashes required (default)'), (2, 'No dashes required (least strict)')], default=1),
        ),
    ]
