# Generated by Django 2.0.6 on 2018-06-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180619_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='redacted',
            new_name='redact_file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='note',
            new_name='redaction_note',
        ),
        migrations.AddField(
            model_name='feature',
            name='redact_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='redaction_note',
            field=models.TextField(blank=True),
        ),
    ]
