# Generated by Django 2.0.6 on 2018-06-19 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180619_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_only', models.BooleanField(default=False)),
                ('redacted_set_path', models.TextField(blank=True)),
                ('be_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redacted_sets', to='api.BESession')),
            ],
        ),
    ]
