# Generated by Django 2.0.6 on 2018-06-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_redactedset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besession',
            name='be_complete',
        ),
        migrations.RemoveField(
            model_name='besession',
            name='dfxml',
        ),
        migrations.RemoveField(
            model_name='besession',
            name='features_annotated',
        ),
        migrations.AddField(
            model_name='besession',
            name='processing_failure',
            field=models.BooleanField(default=False),
        ),
    ]
