# Generated by Django 2.0.6 on 2018-06-25 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180625_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besession',
            name='in_process',
        ),
        migrations.AddField(
            model_name='besession',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
