# Generated by Django 2.0.6 on 2018-06-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180625_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source_path',
            field=models.FilePathField(allow_folders=True, path='/src/transfers/', recursive=True),
        ),
    ]
