# Generated by Django 2.0.6 on 2018-06-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180627_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source_path',
            field=models.FilePathField(allow_folders=True, path='/transfers/'),
        ),
    ]
