# Generated by Django 2.0.6 on 2018-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_besession_extracted_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besession',
            name='transfer',
        ),
        migrations.AddField(
            model_name='besession',
            name='disk_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='besession',
            name='source_path',
            field=models.FilePathField(allow_folders=True, default='/transfers/samplefile', path='/transfers/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
