# Generated by Django 2.0.6 on 2018-06-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180628_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besession',
            name='source_path',
            field=models.FilePathField(allow_folders=True, path='/data/transfers/'),
        ),
    ]
