# Generated by Django 2.0.6 on 2018-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180628_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
