# Generated by Django 2.0.6 on 2018-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180628_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redactedset',
            name='log_only',
        ),
        migrations.AddField(
            model_name='redactedset',
            name='redaction_type',
            field=models.IntegerField(choices=[(0, 'Log only'), (1, 'Remove files'), (2, 'Redact features (scrub)'), (3, 'Redact features (replace)'), (4, 'Redact features within disk image')], default=1),
        ),
    ]
