# Generated by Django 2.0.6 on 2018-06-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180628_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactedset',
            name='unallocated_files',
            field=models.BooleanField(default=False),
        ),
    ]
