# Generated by Django 2.0.6 on 2018-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_redactedset_unallocated_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactedset',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redactedset',
            name='processing_failure',
            field=models.BooleanField(default=False),
        ),
    ]
