# Generated by Django 2.0.6 on 2018-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180628_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
