# Generated by Django 2.0.6 on 2018-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180629_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactedset',
            name='redaction_log',
            field=models.TextField(blank=True),
        ),
    ]
