# Generated by Django 2.0.6 on 2018-07-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_redactedset_redaction_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='redaction_note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='redaction_note',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='redact_feature',
        ),
        migrations.RemoveField(
            model_name='file',
            name='redact_file',
        ),
    ]
