# Generated by Django 2.0.6 on 2018-07-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_file_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='beconfig',
            name='exif_gps_scanners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beconfig',
            name='pii_scanners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beconfig',
            name='web_scanners',
            field=models.BooleanField(default=False),
        ),
    ]
