# Generated by Django 2.0.6 on 2018-07-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180721_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besession',
            name='source_path',
            field=models.TextField(),
        ),
    ]
