# Generated by Django 2.0.6 on 2018-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180725_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedset',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
