# Generated by Django 2.0.9 on 2018-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20181030_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedset',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
