# Generated by Django 2.0.9 on 2018-11-17 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20181112_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_type', models.CharField(max_length=50)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.File')),
            ],
        ),
    ]
