# Generated by Django 2.0.9 on 2018-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20181117_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedentity',
            name='name',
        ),
        migrations.AddField(
            model_name='namedentity',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='namedentity',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
