# Generated by Django 2.0.9 on 2018-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20181117_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='besession',
            name='named_entity_extraction',
            field=models.BooleanField(default=False),
        ),
    ]
