# Generated by Django 2.0.9 on 2018-11-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_besession_named_entity_extraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedentity',
            name='source_file',
        ),
        migrations.DeleteModel(
            name='NamedEntity',
        ),
    ]
