# Generated by Django 2.0.9 on 2018-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20181117_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
